<a href="https://colab.research.google.com/github/jalbury/machine-learning/blob/master/HW_4/HW4_Problem2_John_Albury.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Imports

In [0]:
import numpy as np

# Problem 2 Description

In this problem, we are asked to implement a function `maxpooling2d` that takes as input an input matrix (`input_mat`) and a window size (`s`) and outputs the result of the maxpooling (`output_mat`).

The given input matrix must be square; if it is not, an exception is thrown. If the given input matrix is smaller than the given window size, an exception is thrown.

To obtain the maximum value in a matrix when performing maxpooling, I used the `np.max()` function.

# Solution

## Implementation

In [0]:
# Custom exception to handle a non-square matrix being given
class NonSquareMatrixError(Exception):
  def __init__(self, shape):
    self.shape = shape
  def __str__(self):
    return "Input matrix is not a square matrix (has shape {})".\
            format(self.shape)

# Custom exception to handle invalid window size being given
class InvalidWindowSize(Exception):
  def __init__(self, window_size):
    self.window_size = window_size
  def __str__(self):
    if self.window_size < 0:
      return "Window size must be greater than 0"
    else:
      return "Window size must be less than or equal to size of input matrix"

# Checks that the given array is a square matrix. If it is not, a custom
# exception is thrown.
def is_square_matrix(mat):
  if len(mat.shape) != 2 or mat.shape[0] != mat.shape[1]:
    raise NonSquareMatrixError(mat.shape)

def maxpooling2d(input_mat, s):
  # Make sure that both given arrays are square matrices
  is_square_matrix(input_mat)

  # Make sure that window size is valid
  if s < 0 or s > input_mat.shape[0]:
    raise InvalidWindowSize(s)

  # Get number of rows/columns in input matrix
  input_size = input_mat.shape[0]

  # Create output matrix for storing maxpooling result
  output_size = int(np.ceil(input_size / s))
  output_mat = np.empty((output_size, output_size))

  # Created padded version of input array
  num_pad = s - 1
  padded_shape = input_size + num_pad*2
  input_padded = np.zeros((padded_shape, padded_shape))
  input_padded[num_pad : input_size + num_pad,
               num_pad : input_size + num_pad] = input_mat

  # Use sliding window to get every possible patch in input matrix and fill up
  # cells in output matrix with result of maxpooling
  for i in range(0, input_size, s):
    for j in range(0, input_size, s):
      # Get bounds (in terms of padded input matrix rows/cols) for this patch
      min_patch_row = i + num_pad
      max_patch_row = i + (s - 1) + num_pad
      min_patch_col = j + num_pad
      max_patch_col = j + (s - 1) + num_pad
      
      # Get patch from padded input matrix
      patch = input_padded[min_patch_row : max_patch_row + 1, 
                        min_patch_col : max_patch_col + 1]

      # Compute value in output matrix as max value in patch
      output_mat[int(i / s), int(j / s)] = np.max(patch)
  
  return output_mat

## Valid matrix, window size given

In [3]:
input_mat = np.array([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12],
                      [13, 14, 15, 16]])

output_mat = maxpooling2d(input_mat, 2)

print(output_mat)

[[ 6.  8.]
 [14. 16.]]


In [4]:
input_mat = np.array([[19, 2, 3],
                      [6, 12, 7],
                      [8, 4, 10]])

output_mat = maxpooling2d(input_mat, 2)

print(output_mat)

[[19.  7.]
 [ 8. 10.]]


## Non-square matrix given



In [5]:
input_mat = np.array([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]])

output_mat = maxpooling2d(input_mat, 2)

print(output_mat)

NonSquareMatrixError: ignored

## Invalid window size given

In [6]:
input_mat = np.array([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12],
                      [13, 14, 15, 16]])

output_mat = maxpooling2d(input_mat, 5)

print(output_mat)

InvalidWindowSize: ignored

## Test cases

Below are the results of my running my program with the test cases provided in the assignment.

In [7]:
import skimage.measure

input_mat = []
expected_mat = []
s = []
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 4, 2, 1],
                      [1, 2, 4, 2],
                      [2, 1, 2, 1]]))
s.append(2)

expected_mat.append(np.array([[4, 2],
                                [2, 4]]))

input_mat.append(np.array([[1, 2, 1, 2, 4, 5],
                      [2, 4, 2, 1, 0, 3],
                      [1, 2, 4, 2, 4, 5],
                      [2, 1, 2, 1, 2, 1],
                      [1, 1, 2, 3, 1, 2],
                      [1, 1, 2, 3, 1, 2]]))
s.append(2)

expected_mat.append([[4, 2, 5],
 [2, 4, 5],
 [1, 3, 2]])


for i in range(len(input_mat)):
  # uncomment top line and comment second line to test code
  output_mat = maxpooling2d(input_mat[i], s[i])
  # output_mat = skimage.measure.block_reduce(input_mat[i], (s[i],s[i]), np.max)

  print(output_mat)

  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!")
  else:
    print("Incorrect output!")

[[4. 2.]
 [2. 4.]]
Correct output!
[[4. 2. 5.]
 [2. 4. 5.]
 [1. 3. 2.]]
Correct output!
