<a href="https://colab.research.google.com/github/jalbury/machine-learning/blob/master/HW_1/HW1_John_Albury.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CAP 4630 Homework 1

## Problem Description

For this assignment, we are asked write a `multiply_matrices` function, which takes in a list of numpy arrays and outputs their product.

Matrix multiplication works by multiplying the elements of the columns of one matrix with the elements of the rows of the other matrix to produce a new matrix. Here, order matters, so for two arbitrary matrices $M_1$ and $M_2$, $M_1M_2$ is not necessarily the same as $M_2M_1$.

In order for two matrices to be multiplied, the matrix on the left side must have the same number of columns as the the matrix on the right side has rows. As a general example, let $M_1 \in \mathbb{R}^{m \cdot n}$ ($m$ rows and $n$ columns) and $M_2 \in \mathbb{R}^{p \cdot q}$ ($p$ rows and $q$ columns). For $M_1M_2$ to be computable, $n$ must equal $p$. If $n=p$, then $M_1M_2 \in \mathbb{R}^{m \cdot q}$.

For this problem, we are assuming that the matrices given are meant to be multiplied sequentially. That is, given a list of matrices [$M_1$, $M_2$, ..., $M_n$], we will output $M_1M_2 \cdot\cdot\cdot M_n$.

## Solution

To solve this problem, I used the numpy `dot()` function, which computes the dot product of two given arrays. For two-dimensional arrays, it is equivalent to matrix multiplication. The `dot()` function is vectorized, meaning it is able to compute the results of the operation in parallel, producing the result much faster than if I sequentially looped through the rows and columns of the matrices to perform the computation. 

After checking to make sure that the list is not `None` and is not empty, I initalize the `product` matrix to be the first matrix in the list. Then, I update `product` by multiplying it by the second matrix in the list. This is repeated for the rest of the matrices in the list to compute the final product of the matrix multiplication. A custom exception is thrown if any of the given matrices cannot be multiplied, telling the user which matrices were the problem and what their dimensions were.

In [0]:
import numpy as np

# custom exception to handle empty list or no list being given
class EmptyMatricesListError(Exception):
  def __str__(self):
    return ("multiply_matrices() requires the given list has at least one "
            "matrix.")

# custom exception to handle incompatible matrices being given
class IncompatibleMatricesError(Exception):
  def __init__(self, index, matrix1_shape, matrix2_shape):
    self.index = index
    self.matrix1_shape = matrix1_shape
    self.matrix2_shape = matrix2_shape
  
  def __str__(self):
    msg = "Cannot multiply the given list of matrices. "
    if self.index <= 1:
      msg += ("Matrix 1 has dimensions {}, while matrix 2 has dimensions "
              "{}.".format(self.matrix1_shape, self.matrix2_shape))
    else:
      msg += ("The product of matrices 1 through {} has dimensions {}, while "
              "matrix {} has dimensions {}".format(self.index,
                                                   self.matrix1_shape,
                                                   self.index+1,
                                                   self.matrix2_shape))
    return msg

def multiply_matrices(matrices):
  # make sure we're given at least 1 matrix
  if matrices is None or len(matrices) == 0:
    raise EmptyMatricesListError
  
  # initialize resulting product with the first matrix in the list
  product = matrices[0]

  for i in np.arange(1, len(matrices)):
    # make sure the matrices are compatible
    if product.shape[1] != matrices[i].shape[0]:
      raise IncompatibleMatricesError(i, product.shape, matrices[i].shape)

    # multiply current product by the next matrix in the list
    product = product.dot(matrices[i])

  return product

## Examples

Below are some examples of the output when a valid list of matrices is given.

In [35]:
a = np.array([[1, 2, 0], 
              [3, 4, 4]])
b = np.array([[2, 4], 
              [1, 5],
              [6, 8]])
c = np.array([[4, 2, 7],
              [7, 2, 1],
              [2, 0, 3]])
d = np.array([[2, 1, 0, 4],
              [3, 4, 7, 1]])

print("Example 1:")
print(multiply_matrices([a, b]))

print("\nExample 2:")
print(multiply_matrices([a, c, b]))

print("\nExample 2:")
print(multiply_matrices([a, c, b, d]))

Example 1:
[[ 4 14]
 [34 64]]

Example 2:
[[ 96 174]
 [332 558]]

Example 2:
[[ 714  792 1218  558]
 [2338 2564 3906 1886]]


The example below shows the result of an empty list being given.

In [36]:
multiply_matrices([])

EmptyMatricesListError: ignored

The example below shows the result of some of the matrices in the list being incompatible.

In [37]:
a = np.array([[1, 2, 0], 
              [3, 4, 4]])
b = np.array([[2, 4], 
              [1, 5],
              [6, 8]])
c = np.array([[4, 2, 7],
              [7, 2, 1],
              [2, 0, 3]])

multiply_matrices([a, b, c])

IncompatibleMatricesError: ignored